language: python

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - cmake
    - curl
    - freeglut3-dev
    - g++
    - g++-aarch64-linux-gnu
    - g++-arm-linux-gnueabihf
    - gperf
    - libbz2-dev
    - libegl1-mesa-dev
    - libfreetype6-dev
    - libgl1-mesa-dri
    - libgles2-mesa-dev
    - libglib2.0-dev
    - libglu1-mesa-dev
    - libosmesa6-dev
    - libssl-dev
    - libxmu-dev
    - libxmu6
    - python-pip
    - python-virtualenv
    - xorg-dev

cache:
  directories:
    - .cargo
    - .servo
    - $HOME/.ccache

env:
  global: CCACHE=/usr/bin/ccache
  matrix:
  - BUILD_TARGET=x86_64-unknown-linux-gnu TRIPLET=x86_64-linux-gnu
  - BUILD_TARGET=arm-unknown-linux-gnueabihf TRIPLET=arm-linux-gnueabihf PKG_CONFIG_ALLOW_CROSS=1 PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig
  - BUILD_TARGET=aarch64-unknown-linux-gnu TRIPLET=aarch64-linux-gnu PKG_CONFIG_ALLOW_CROSS=1 PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig

before_script:
  - mkdir $HOME/bin
  - for f in /usr/bin/arm-linux-*; do f2=$(basename $f); ln -s $f $HOME/bin/${f2/-linux/-unknown-linux}; done
  - for f in /usr/bin/aarch64-linux-*; do f2=$(basename $f); ln -s $f $HOME/bin/${f2/-linux/-unknown-linux}; done
  - PATH="$HOME/bin:$PATH"
  - git clone https://github.com/servo/servo --depth=10
  - sed -i "s/stdlibs = \[host_triple(), \"arm-linux-androideabi\"\]/stdlibs = set(\[host_triple(), \"arm-linux-androideabi\", \"$BUILD_TARGET\"\])/" servo/python/servo/bootstrap_commands.py

script:
  - cd servo
  - ./mach build --rel --target=$BUILD_TARGET

before_deploy:
  - cd $TRAVIS_BUILD_DIR/servo
  - tar czf servo-$TRIPLET-$(date '+%Y-%m-%d').tgz --transform 's|target/'$BUILD_TARGET'/release/||' target/$BUILD_TARGET/release/servo target/$BUILD_TARGET/release/libservo.rlib resources

deploy:
  provider: releases
  api_key:
    secure: Hy7xye62EmDnFwpkNiVMML+Tkq31nuAoHTHUdT5nh7R9eYSuUvvkOa3SWnCjyOiQNT1W4o2aPYH7JFX8229pdCPvWixKhFabj251v0RszxfHxXsdSWFeGqoh7nRDQ/ur+m+lZdlpBE1OCTLa66h8mjggv2KJwffbhpRpFH9xyIpD3immG3q681GeLbP7QlR4gt8J3KYyJGCpcFK7SYXM1fEIk7EwHf+usouoqrkA7j3hmjPrifwJv5sOJ4K5V2WgfLVb5xIx6fB3JK7SASswjdUMBYguI1QKhQvK1Shn0TjHWn08mInEf6+s9nfP3QgSsDw+4bfxe0OnxAdRmz9PHLXI9Ij7pH9QVMYTzHRqRIBgQ4VWp0++Kj5rYqVr1W3QyCpZk8AmFVwlCnhC+eXxxtsWWckG/D9xEiBSrghH2fAtVJoMkcRC001FQWG/8u0tTS9G8kYD4Esr6SJyIRk6kUxySERC48+zSJ1Xk56Vikfc36pny3hY3LdNMWCI2GvlddM6EduLgpP2+3N11ljUC2otmkRbRSsyUPgjmpXRcHSp2eCOZ3EWXHDs4FM96z9LpUnJYna2XAop3XIItjle1Gphraqt6wiMaNedjRsvRxmEcQwpyfVSxokQr6T1iDydVgsQPNAPuUSYN3ThdtpoXzol11PKHcRJ7onWwsivR1U=
  file: $TRAVIS_BUILD_DIR/servo/servo-$TRIPLET-$(date '+%Y-%m-%d').tgz
  skip_cleanup: true
  on:
    tags: true
