language: python

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - cmake
    - curl
    - freeglut3-dev
    - g++
    - g++-aarch64-linux-gnu
    - g++-arm-linux-gnueabihf
    - gperf
    - libbz2-dev
    - libegl1-mesa-dev
    - libfreetype6-dev
    - libgl1-mesa-dri
    - libgles2-mesa-dev
    - libglib2.0-dev
    - libglu1-mesa-dev
    - libosmesa6-dev
    - libssl-dev
    - libxmu-dev
    - libxmu6
    - python-pip
    - python-virtualenv
    - xorg-dev
    # for Android:
    - ant
    - expect
    - lib32gcc1
    - lib32stdc++6
    - lib32z1
    - openjdk-7-jdk

cache:
  directories:
    - .cargo
    - .servo
    - $HOME/.ccache

env:
  global:
  - CCACHE=/usr/bin/ccache
  - secure: "BrOSmP3TOYc0on+agtR00EY0pXas5Y2pNCVAhb+mUR3YP9BZBOG37mYVX1lYUo2Kk4HClb5ocCWqB3LzIkXcUoc9kU3L3ec5dkiXPuHlCi/JOkp09xfxlNQOEPr4D1yZXcw2NyBHxe8NnWjCue8JOdbx4DdSgqTs1g42cjoB3CsrGruxn11GmxTtvQxNcwUcNpBsbZADgO1VQbc/df8fpuTF90zV9AcYKgF9Y5zW+87lQIC3neUsw+8+oR72vtLMvSLfnyGSjxuULN82j+9GUHyoLMuFjiZTmbUpiirW6WYSgHD8Qzg6HsecesQDkktJUzk//stXy9SAqHxXk3dob6Stv3gkYUx9ErGeoe3QKZWTJKgygMJMvkriA1jEcjRA2E6rpSzksnxp4eDfqgOu+SkUmzjHYIL771+tDRSfn5Zipx7zYpAyZmWhl+8lGT+hSzQTjZBvyGHh0N5r7Rq79OmJN5loHlHsd8BlCkfs9BsbYJsIntaApGmEmFUohG5s/i1S8nbGXPIYqfMHHykNX45Wzv08L2HSinw7Y9nflouv0wMGLvAOOdUA+FRsaxdrINgwJSAQjB+57lsCLYuVm2FD4+VxQE/qJbdeSwDdds76gKOrb8R4KlZ77Xl+kOuOXP5tVWSJDnLb8CY7dOiPZXCbn7txoRkYHc6x19E69XY="
  matrix:
  - BUILD_TARGET=x86_64-unknown-linux-gnu TRIPLET=x86_64-linux-gnu
  - BUILD_TARGET=arm-unknown-linux-gnueabihf TRIPLET=arm-linux-gnueabihf PKG_CONFIG_ALLOW_CROSS=1 PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig
  - BUILD_TARGET=aarch64-unknown-linux-gnu TRIPLET=aarch64-linux-gnu PKG_CONFIG_ALLOW_CROSS=1 PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
  - BUILD_TARGET=arm-linux-androideabi TRIPLET=arm-linux-androideabi

before_script:
  - mkdir $HOME/bin
  - for f in /usr/bin/arm-linux-*; do f2=$(basename $f); ln -s $f $HOME/bin/${f2/-linux/-unknown-linux}; done
  - for f in /usr/bin/aarch64-linux-*; do f2=$(basename $f); ln -s $f $HOME/bin/${f2/-linux/-unknown-linux}; done
  - PATH="$PATH:$HOME/bin"
  - git clone https://github.com/servo/servo --depth=10
  - sed -i "s/stdlibs = \[host_triple(), \"arm-linux-androideabi\"\]/stdlibs = set(\[host_triple(), \"arm-linux-androideabi\", \"$BUILD_TARGET\"\])/" servo/python/servo/bootstrap_commands.py
  - if [[ "$BUILD_TARGET" == "arm-linux-androideabi" ]]; then source setup_android.sh; fi

script:
  - cd servo
  - ./mach build --rel --target=$BUILD_TARGET

after_success:
  - cd $TRAVIS_BUILD_DIR/servo
  - export ASSET_NAME=servo-$TRIPLET-$(date '+%Y-%m-%d').tgz
  - tar czf $ASSET_NAME --transform 's|target/'$BUILD_TARGET'/release/||' target/$BUILD_TARGET/release/servo target/$BUILD_TARGET/release/libservo.rlib resources
  - cd ..
  - ./upload_to_github.py
