language: python

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - cmake
    - curl
    - freeglut3-dev
    - g++
    - g++-aarch64-linux-gnu
    - g++-arm-linux-gnueabihf
    - gperf
    - libbz2-dev
    - libfreetype6-dev
    - libgl1-mesa-dri
    - libglib2.0-dev
    - libglu1-mesa-dev
    - libosmesa6-dev
    - libssl-dev
    - libxmu-dev
    - libxmu6
    - python-pip
    - python-virtualenv
    - xorg-dev

cache:
  directories:
    - .cargo
    - .servo
    - $HOME/.ccache

env:
  global: CCACHE=/usr/bin/ccache
  matrix:
  - BUILD_TARGET=x86_64-unknown-linux-gnu
  - BUILD_TARGET=arm-unknown-linux-gnueabihf
  - BUILD_TARGET=aarch64-unknown-linux-gnu

before_script:
  - git clone https://github.com/servo/servo --depth=10
  - sed -i "s/stdlibs = \[host_triple(), \"arm-linux-androideabi\"\]/stdlibs = set(\[host_triple(), \"arm-linux-androideabi\", \"$BUILD_TARGET\"\])/" servo/python/servo/bootstrap_commands.py

script:
  - cd servo
  - ./mach build --rel --target=$BUILD_TARGET
